### ISSUE TITLE
Dubwool Can "Eat" Items

### ISSUE THREAD

**Issue by Soosage** [ObliqueNET/Server#591] opened 2020-07-04 06:38 UTC
Not 100% sure this is the right place to report bugs like this but

Right clicking on a caught Dubwool with a non-held item in hand causes the item to vanish. After right clicking my Dubwool by accident I noticed my axe disappeared from my inventory. Tested with cobblestone blocks, pokeballs, and buckets, all of which disappeared. Stackable items get consumed one by one. Right clicking with an intended held item such as Silk Scarf will correctly place it in Dubwool's held item slot. Another player confirmed they were getting the same result using wooden shovels.

**Comment by starwarschamp4** [comment] 2020-07-04 07:02
If this also happens in single player, report that here: https://pixelmonmod.com/tracker.php?p=2

**Comment by Christodynamics** [comment] 2020-07-04 17:24
Confirmed happening in singleplayer. Posted on Pixelmon tracker. https://pixelmonmod.com/tracker.php?p=2&t=14809 

Could be marked as solved as not an Oblique bug.

**Comment by Vohras2** [comment] 2020-07-05 17:28
Closing, since posted on pixelmon bug tracker.

**Closed by Vohras2** 2020-07-05 17:28 UTC
Labels: bug
