### ISSUE TITLE
[LandLord] Master command ticket 

### ISSUE THREAD

**Issue by NukingLizards** [ObliqueNET/Server#922] opened 2020-12-28 16:07 UTC
I and a fellow player CptCovenant have found some bugs and command issues with the LandLord Plugin. The issues so far are:

- /t demote player (can not demote players)
- /plot create open (so outsiders can claim plots)
- /outpost list (only shows one page of outposts. If you have a bigger town with more outposts you cant view them)

![image](https://user-images.githubusercontent.com/64395766/103227504-38a35c80-497a-11eb-8392-b90cd139e47d.png)

![image](https://user-images.githubusercontent.com/64395766/103227564-625c8380-497a-11eb-9dc2-81288e6c7380.png)

please Dm me on discord for more information

Kind regards,

Nuking_Lizards

**Comment by kevvikev** [comment] 2021-01-09 12:50
![image](https://user-images.githubusercontent.com/77196893/104092011-2a452280-524f-11eb-83f4-0c021959b95c.png)

when i try to bring up the outpost list i get this error code. the rest of the town have this problem as well.

**Comment by Rasgnarok** [comment] 2021-01-13 18:48
https://github.com/ObliqueNET/Server/issues/944

Kicking offline (uncached) player. Will need to test the error in console first. Closing linked ticket in favour of masterticket.

**Comment by Hiroku** [comment] 2021-01-14 11:50
For the plot create bug, the price is meant to come before the "open" option. Not a bug, just misunderstanding the command

**Comment by NukingLizards** [comment] 2021-01-14 11:56
> For the plot create bug, the price is meant to come before the "open" option. Not a bug, just misunderstanding the command

Seems to work please update command list:

https://github.com/ObliqueNET/Server/wiki/Landlord-Commands

/plot create open (price) - Creates a plot for the anyone, even outsiders from a town, to purchase.

**Comment by Hiroku** [comment] 2021-01-14 11:58
I've fixed the documentation error, thank you

**Comment by Quadehar97** [comment] 2021-02-07 13:02
Cannot use multiple outposts cause of no second page when we have the ability to make more

**Comment by Vohras2** [comment] 2021-05-18 17:51
Closing this, as all of this has been patched as far as I'm aware.

**Closed by Vohras2** 2021-05-18 17:51 UTC
Labels: bug, landlord, needs testing
