### ISSUE TITLE
Legendary turned into normal pokemon when caught?

### ISSUE THREAD

**Issue by tkdowning** [ObliqueNET/Server#1164] opened 2021-07-08 16:45 UTC
So I was sitting in an ice plains biome and a Gastrier spawned on me. Both me and Jah went looking for it and when I found it, I immediately threw a park ball at it. We both saw a big grey ice horse. But when I caught it, it turned into a Bergmite.... Unfortunately I don't have any proof and when the caught message appeared it said "bergmite was caught." Not too sure what happened but I do know that I am confused... tkdowning

**Comment by Rasgnarok** [comment] 2021-08-06 18:26
I honestly can't do much about this one. It sounds like a storage issue, but if I can't reproduce it, I can't fix it. If I don't have proof, I also can't refund it. Closing.

**Closed by Rasgnarok** 2021-08-06 18:26 UTC
