### ISSUE TITLE
Mobs  being despawned

### ISSUE THREAD

**Issue by Boxman1010** [ObliqueNET/Server#531] opened 2020-05-20 03:20 UTC
It seams me and a few others have been having issues with horses and horse like animals such as mules and donkeys disappearing even while named tamed and having say saddles etc on them i personally lost 2 sets of animals now because after the first time a mod had gave them back to me in spawn egg form i respawned renamed and got them back but they seam to have despawned again even when being named etc. Another person had said that they disappeared when the server lagged like they just vanished in a lag spike.

**Comment by Blastblaze1** [comment] 2020-05-20 03:45
I can confirm, I was the person who lost my (Nametagged) mule when the server had a small lag spike. I was riding it around for quite a while at the time, and when the lag hit I was dismounted from it and the mule was nowhere in sight. I relogged and restarted my launcher to make sure that it wasn't just invisible, but it was still completely gone when I got back.

**Comment by Rasgnarok** [comment] 2021-01-13 19:07
Closing as I can't reproduce. Likely caused by old Sponge bugs within our Landlord protection plugin. Should be fixed as of the latest overhaul. Please open a new ticket if the issue persists.

**Closed by Rasgnarok** 2021-01-13 19:07 UTC
Labels: landlord, needs testing, sponge
