### ISSUE TITLE
[Sponge] Landlord NPE when world is unloaded 

### ISSUE THREAD

**Issue by kevvikev** [ObliqueNET/Server#940] opened 2021-01-10 13:12 UTC
![image](https://user-images.githubusercontent.com/77196893/104123852-7198e500-531b-11eb-94a3-4fdf4ef6a89d.png)

When me and the rest of the town try and open the outpost list we get this error message

**Comment by Rasgnarok** [comment] 2021-01-13 18:42
Duplicate, but I am keeping this one as this is a **Sponge** issue, not Landlord. Posted in https://github.com/ObliqueNET/Server/issues/922 originally. For now, the workaround is you warping to the world in question, and _then_ doing `/t outpost`. This is caused by Sponge not keeping the world loaded. I'll try and see if I can work around it.

https://github.com/ObliqueNET/Server/issues/922#issuecomment-757153321

**Comment by Rasgnarok** [comment] 2021-01-13 18:43
https://github.com/ObliqueNET/Server/issues/880

**Comment by Rasgnarok** [comment] 2021-01-13 21:27
For @Rasgnarok 
`/world load DIM1/DIM-1`
`/world setloadonstartup DIM1/DIM-1 true`
`/world setkeepspawnloaded DIM1/DIM-1`

Has kept worlds loaded for the last 2 hours, but might not persist on restart. Will need to be looked at when we routine restart tonight.

**Comment by Rasgnarok** [comment] 2021-01-14 12:59
Fixed as of this new restart.

**Closed by Rasgnarok** 2021-01-14 12:59 UTC
Labels: bug, sponge
