### ISSUE TITLE
Wiki mia staff thing not working correctly

### ISSUE THREAD

**Issue by Bluespider20** [ObliqueNET/Server#601] opened 2020-07-15 03:24 UTC
When I was trying to direct a player to the Pixelmon wiki for how to make a camera by saying Mia Pixelmon wiki camera in chat, my name and all of my tags were added into the search.

![Mia issue](https://user-images.githubusercontent.com/68312670/87499819-bb309d80-c620-11ea-8a23-16bd63187714.png)

I tried reproducing it 1-2 hours later and it worked perfectly fine but thought you might want to know.

**Comment by Hiroku** [comment] 2020-07-15 12:46
If it can be reproduced at all then I'll take a look, but nothing jumps out at me as a cause yet

**Comment by Rasgnarok** [comment] 2020-09-02 18:49
![image](https://user-images.githubusercontent.com/18584380/92023875-64476a80-ed2b-11ea-9997-fc580af0422f.png)
am thinking it either took the full line, or something went particularly wrong that day. Closing because I can't reproduce.

**Closed by Rasgnarok** 2020-09-02 18:49 UTC
