### ISSUE TITLE
Immortal Skeletons

### ISSUE THREAD

**Issue by the4bestgame** [ObliqueNET/Server#828] opened 2020-10-24 13:45 UTC
In the mob world Heill Passive mobs are immortal, presumably because we have no need to kill them. However in the quest "the mailman" we have to kill skeletons in the cave at -35 43 -90. These skeletons also find themselves blessed with an inability to die, rendering the quest incompletable and my body full of arrows from attempting to slay them.

TL:DR Skeletons in mob world can't be killed. Test it at  -35 43 -90,lolsikinz can confirm

**Comment by starwarschamp4** [comment] 2020-11-02 21:43
I have just tested the skeletons at this location, and I am able to kill them (ignoring claims if off btw). If it doesn't work for you, bows work in admin claims to kill anything :P

**Comment by starwarschamp4** [comment] 2020-11-17 18:54
Removed the skeleton killing objective as you still can't kill skeletons in admin claims for some reason. Also removed the spawners for them for this same issue. However, the bug still exists so will keep this open.

**Comment by Rasgnarok** [comment] 2021-01-13 19:08
Duplicate of https://github.com/ObliqueNET/Server/issues/526, closing in favour of creating a more complete ticket.

**Closed by Rasgnarok** 2021-01-13 19:08 UTC
Labels: bug, duplicate, landlord, sponge
